google/play-services-plugins

- .travis.yml
- strict-version-matcher-plugin/build.gradle
- strict-version-matcher-plugin/gradle.properties
- strict-version-matcher-plugin/gradle/wrapper/gradle-wrapper.properties
- strict-version-matcher-plugin/publish.gradle
These changes enable Travis CI building.
TESTED=Both builds show green on my GitHub fork.
> Enable Travis CI

- strict-version-matcher-plugin/src/main/java/com/google/android/gms/dependencies/DataObjects.kt
- strict-version-matcher-plugin/src/main/java/com/google/android/gms/dependencies/VersionEvaluation.kt
This version of the connector was backward compatible so adding an
exclusion to prevent build errors for users.
> Add exclusion for the connector's 16 -> 17 major version bump.

- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/LicensesTask.groovy
- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/LicensesTaskTest.java
Fix #3.
The issue is caused because the content of `third_party_licenses` are encoded with JVM's default file encoding while content lengths are brought from `third_party_licenses.json` for Google Play services dependencies. If JVM's default encoding is not UTF-8 (it's likely on Windows machines), content length defined in `third_party_licenses_metadata` and actual length in `third_party_licenses` can be misaligned and heading characters of following contents can be missing.
- Explicitly encode strings with UTF-8 before appending them to file
- For Google Play services dependencies, avoid unnecessary decoding & encoding and use bytes read from `third_party_licenses.txt` as-is
The issue can be reproduced by changing JVM's default encoding. For example, adding `-Dfile.encoding=xxx` option …
> Make sure to encode strings with UTF-8 even if JVM's default encoding is not UTF-8

- strict-version-matcher-plugin/src/main/java/com/google/android/gms/dependencies/DependencyInspector.java
The root module's path is ":" and therefore it's display name is "project :".
Calling split(":")[1] on "project :" causes "java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1" to be thrown.
> Handled the root module's display name

- google-services-plugin/README.md
- google-services-plugin/bintray.gradle
- google-services-plugin/build.gradle
- google-services-plugin/publish.gradle
- google-services-plugin/src/main/resources/META-INF/gradle-plugins/com.google.gms.google-services.properties
#50
If this will get merged I can do the same for the other two plugins. `oss-licenses-plugin` would have to be migrated from `maven` to `maven-publish` plugin though.
> Publish plugin marker artifact for google-services-plugin

- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesTask.java
👋hi! I've been working on making my app's Gradle builds fully incremental, and I noticed this message from Gradle (when running with `--info`):
```
> Task :app:processInternalDebugGoogleServices
Caching disabled for task ':app:processInternalDebugGoogleServices': Caching has not been enabled for the task
Task ':app:processInternalDebugGoogleServices' is not up-to-date because:
Task has not declared any outputs despite executing actions.
```
It looks like `GoogleServicesTask` has annotated its inputs and outputs as Gradle requires for its `UP-TO-DATE` checks to work, but Gradle only recognizes these annotations when they're on methods (not fields), so they're not having an effect. (See https://docs.gradle.org/5.4.1/javadoc/org/gradle/api/tasks/InputFile.html)
This PR replaces the public …
> Move input and output annotations to methods to fix incremental execution

- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesPlugin.groovy
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/OssLicensesPlugin.groovy
Addresses https://github.com/google/play-services-plugins/issues/57
> Prefer newer lazy task configuration gradle api for merge resources

- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesPlugin.groovy
I debugged the plugin to find that `variant.respondsTo("mergeResourcesProvider")` returns an empty collection, presumably because the actual method is called `getMergeResourcesProvider`, thought Groovy allows you to drop the `get`.
Fixes #65
> Fixes `getMergeResourcesProvider` query name so plugin doesn't use deprecated APIs.

- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/LicensesTask.groovy
- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/LicensesTaskTest.java
- oss-licenses-plugin/src/test/resources/dependencies/groupE/deps5.pom
- oss-licenses-plugin/src/test/resources/dependencies/groupE/deps5.txt
Fixes #6.
I've included a testcase that failed before the change and passes afterward. I don't really understand all the nuances of the test setup here so please let me know if this could be done better.
> Fix handling of .pom files with multiple license declarations

- .travis.yml
This was disabled in 074d32, and I'm not sure why, but it might be
because the oss-licenses-plugin only seems to work with JDK 8, so maybe
that just was not the default.
> Enable CI on OSS Licenses plugin

- google-services-plugin/build.gradle
- strict-version-matcher-plugin/build.gradle
- strict-version-matcher-plugin/src/main/java/com/google/android/gms/dependencies/DependencyAnalyzer.java
- strict-version-matcher-plugin/src/main/java/com/google/android/gms/dependencies/VersionEvaluation.kt
- strict-version-matcher-plugin/src/test/java/com/google/android/gms/dependencies/DependencyAnalyzerTest.java
- strict-version-matcher-plugin/src/test/java/com/google/android/gms/dependencies/TestUtil.kt
- strict-version-matcher-plugin/src/test/java/com/google/android/gms/dependencies/VersionEvaluationTest.java
Strict version matcher should ignore non-google dependencies.
> Strict Version Matcher fix for non-google deps

- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesTask.java
I propose dropping the "level" of the "Parsing json file ..." progress/status message from a _warning_ message to an _info_ message. Any output from a Gradle task causes the task line, the message, and a blank line to be added to the output; whereas tasks with no output are "wiped" or overwritten. This "noise" in the output competes with real warnings, and other messages that we shouldn't ignore. As this message carries no corrective action to be taken, I don't believe that a "warning" is appropriate.
> Downgrade progress message from warning to info level

- .gitignore
- oss-licenses-plugin/build.gradle
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/DependencyTask.groovy
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/LicensesTask.groovy
- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/DependencyTaskTest.java
Fixes #119 
When attempting to call getResolvedArtifacts() on a top level ResolvedConfiguration for an application project that also has library projects an AmbiguousVariantSelectionException will throw. Gradle cannot determine which variant of the library project it should evaluate for artifacts. None of the library project variants lead to artifacts supported by this tool.
This change avoids that by stepping over the library project itself and recursively walking the library project's dependencies. If the library project depends on other library projects, they are avoided in the same way. Once a direct, non-library-project dependency is reached, getAllModuleArtifacts() returns the self-inclusive artifact tree stemming from it.
The result is the set of transitive external dependencies of …
> Missing dependencies

- strict-version-matcher-plugin/src/main/java/com/google/android/gms/dependencies/DataObjects.kt
- strict-version-matcher-plugin/src/test/java/com/google/android/gms/dependencies/DataObjectsTest.kt
Using a List means any dependency encountered more than once will be stored multiple times which unnecessarily consumes memory. The class API returns a Set for the dependency list, so using a Set internally does not alter the behavior of the class whilst giving a memory saving on dependency graphs where the same relationship might be encountered multiple times (e.g. over the course of multiple builds)
I've added a test which demonstrates the duplicate use problem. With the existing code this test will fail due to storing multiple copies of the same relationship.
> Use a Set rather than a List to store dependency relationships

- oss-licenses-plugin/README.md
- oss-licenses-plugin/build.gradle
- oss-licenses-plugin/gradle/wrapper/gradle-wrapper.properties
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/DependencyTask.groovy
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/LicensesCleanUpTask.groovy
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/LicensesTask.groovy
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/OssLicensesPlugin.groovy
- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/DependencyTaskTest.java
- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/LicensesTaskTest.java
This set of changes will make the tasks compatible with Gradle 7 as well as making the tasks cacheable. The largest change was to the DependencyTask class where a new `@Input` annotated method was created. This returns a serializable, sorted list from the set of direct dependencies for the app and any library projects.
Gradle 7 deprecation warnings were based on the use of a Groovy `field` instead of a `property`. Additionally, the previous `@Input` annotated field of `configurations` was not serializable so it could not be used as a key.
```
> Task :app:getDependencies
Type 'DependencyTask': field 'configurations' without corresponding getter has been annotated with @Input. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See …
```
> Make oss-licenses-plugin compatible with Gradle 7

- oss-licenses-plugin/build.gradle
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/DependencyTask.groovy
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/OssLicensesPlugin.groovy
- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/DependencyTaskTest.java
Added handling for dependency cycles for projects by keeping track of previously visited projects and ignoring them if encountered again.
AGP 7.0.0-alpha12 `com.android.tools.build:gradle:7.0.0-alpha12` (possibly other versions) causes projects to list themselves as instances of `ProjectDependency` when iterating over `configuration.allDependencies` for configurations of that project. This causes a self-referential dependency cycle if naively performing a depth-first scan of `configuration.allDependencies` for each project and child project.
fixes #172
> Add oss-licenses-plugin support for dependency cycles in projects

- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesPlugin.groovy
Make the process<Configuration>GoogleServices tasks config avoidant
See https://docs.gradle.org/current/userguide/task_configuration_avoidance.html
This does have the unfortunate side effect of the plugin not complaining about a missing `google-services.json` unless some `process<Configuration>GoogleServices` task gets run somehow.
However, that may be better for local development where the answer of how to get a relevant `google-services.json` can be postponed until after it builds at all. (Though I understand AndroidStudio is capable of handling `google-services.json`, it would still be good for those forced to use CLI development only).
TESTED: Verified by a really simple local android project. Without this change, it complained about `google-services.json` immediately. With this …
> Make the process<Configuration>GoogleServices tasks config avoidant

- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesPlugin.groovy
- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesTask.java
In the process of making configuration of the GooglerServicesTask lazily
configured, the registration of the generated outputs with the Android
Gradle plugin was moved into the task configuration block. This only
works if the google services task is configured before any of the tasks
that consume it, which is not guaranteed, leading to the
This changes also removes the partial workaround of manually adding the
task dependency to one of the consuming tasks.
Issue: https://github.com/google/play-services-plugins/issues/228
Also potentially related: https://github.com/google/play-services-plugins/issues/228
Test: Manually verified that the wiring works correctly with AGP 7.4.0-alpha03 and Gradle 7.5-rc-1
> Fix incorrect wiring of the GoogleServicesTask

- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesTask.java
Add back getIntermediateDir() method for binary compatibility as it
appears the crashlytics plugin depends on that getter.
Bug: https://issuetracker.google.com/237071883
> Fix google services compatibility with crashlytics

- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesPlugin.groovy
- google-services-plugin/src/main/groovy/com/google/gms/googleservices/GoogleServicesTask.java
`google-services.json` was not previously treated as a task input, so changes to that file would not cause the task's UP-TO-DATE check to return `false`. As a result, the generated `values.xml` file is never updated unless `clean` is run after editing the json file, which seems buggy and has customer problems.
See [this issue](https://github.com/firebase/firebase-android-sdk/issues/2191) in the firebase-android-sdk repo, as an example.
> Add google-services.json as a task input, to fix up-to-date checks

- oss-licenses-plugin/build.gradle
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/OssLicensesPlugin.groovy
Calling [notCompatibleWithConfigurationCache](https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#notCompatibleWithConfigurationCache-java.lang.String-) on the `LicensesTask` will prevent the build failure and instead only warn of the issue the first time it is encountered. We do a `respondsTo` method check before calling it. The method was added as incubating in Gradle 7.4 and may be removed in a future version.
We use the Project object during `LicensesTask` execution to query the location of POM files and any Play Services SDKs to extract license information. We don't know which artifact IDs to use in those queries until the AGP task that produces the information has run. It's a bit of a circular problem, but we can at least prevent the build halting error.
Running …
> Add call to notCompatibleWithConfigurationCache to LicensesTask

- google-services-plugin/build.gradle.kts
re: b/313211009
It should be `compileOnly` instead of `implementation`. This prevents the protobuf dependency in `gradle-api` from leaking to the plugin and causing inexpected issues.
> Fix dependency in `gradle-api`

- google-services-plugin/src/main/kotlin/com/google/gms/googleservices/GoogleServicesTask.kt
Make gmpAppId a RegularFileProperty. This will make it easier to consume in the new Crashlytics Gradle plugin. Tested manually.
> Make gmpAppId a RegularFileProperty

- google-services-plugin/README.md
Version 5.0.0 was changed to 4.4.0 before release. Version 4.4.1 is the current version.
> Fix version number

- google-services-plugin/src/main/kotlin/com/google/gms/googleservices/GoogleServicesPlugin.kt
Make the `gmpAppId.txt` output file variant aware. This is to support parallel builds in the latest Crashlytics Gradle plugin, which consumes this output, see https://github.com/firebase/firebase-android-sdk/issues/5962.
> Make gmpAppId variant aware

- .github/workflows/generate_release_rcs.yml
- .github/workflows/main.yml
Our workflows were using not only outdated, but no longer supported versions of the checkout and upload-artifact actions.
> [GithubAction] Bump Github actions to valid versions

- google-services-plugin/build.gradle.kts
Bump version to the next unreleased patch version.
Version 4.4.2 is already released, see https://maven.google.com/web/index.html?q=google-#com.google.gms.google-services:com.google.gms.google-services.gradle.plugin:4.4.2
> Update google-services-plugin version

- oss-licenses-plugin/README.md
- oss-licenses-plugin/build.gradle.kts
This will allow an easier way for users to apply this Gradle plugin using Gradle best pratices https://docs.gradle.org/current/userguide/best_practices_general.html#use_the_plugins_block
Fixes https://github.com/google/play-services-plugins/issues/50
> Enable publishing plugin marker

- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/LicensesTaskTest.java
Before this change LicensesTaskTest was using src/test/resources as Gradle project directory. This means it was leaving stray src/test/resources/userHome/ directory around every time this test was run. Instead, move to a new temporary directory.
Test: ./gradlew test
> Fix LicensesTaskTest from leaving stray files in source tree

- .github/workflows/generate_release_rcs.yml
- oss-licenses-plugin/build.gradle.kts
- strict-version-matcher-plugin/build.gradle.kts
Make all plugins use the same publish configuration to make it easier to release
> Unify publishing mechanism

- oss-licenses-plugin/build.gradle.kts
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/DependencyTask.groovy
- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/LicensesTask.groovy
- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/EndToEndTest.kt
- Makes sure that json and he generated resource files have deterministic order sorted by maven group and artifact name
- Add tests to ensure golden outputs
- Run tests in parallel if there are enough cores on the machine
> Ensure deterministic output for oss-licenses-plugin

- google-services-plugin/build.gradle.kts
- google-services-plugin/gradle/wrapper/gradle-wrapper.properties
We keep compatibility with Kotlin language 1.7 and use stdlib 1.7.10 making sure there is no effect on end users.
Test: ./gradlew test
> Upgrade KGP from 1.7.22 to 2.1.0

- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/LicensesCleanUpTask.groovy
- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/EndToEndTest.kt
Fixes #330
Test: Added a new test
> Make sure clean task skips when there is nothing to clean

- oss-licenses-plugin/build.gradle.kts
Bump the oss licenses plugin version for new release.
> Bumpd oss licenses plugin version to 0.10.9.

- oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/OssLicensesPlugin.groovy
- oss-licenses-plugin/src/test/java/com/google/android/gms/oss/licenses/plugin/EndToEndTest.kt
Use `Sources#res` instead of `Sources#resources` when wiring `LicensesTask`.
Fixes #346
> Wire `LicensesTask` to Android resources source set
